apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-udp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-dns-ip
spec:
  type: LoadBalancer
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-tcp
  namespace: kube-system
  annotations:
    metallb.universe.tf/allow-shared-ip: kube-dns-ip
spec:
  type: LoadBalancer
  selector:
    k8s-app: kube-dns
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153