apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-my-canary
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "x-my-canary"
    nginx.ingress.kubernetes.io/canary-by-header-value: "do-it"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-canary.com
      http:
        paths:
        - path: /web
          backend:
            serviceName: web-svc-v2
            servicePort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc-v2
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: web-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-v2
  name: web-v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-v2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: web-v2
    spec:
      containers:
        - name: web
          image: jndogan/web:1.0.0
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
          livenessProbe:
            tcpSocket: 
              port: 8000
          volumeMounts:
            - name: app
              mountPath: /app
      initContainers:
        - name: init-index-page
          image: busybox:1.31.0
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
          volumeMounts:
            - name: app
              mountPath: /app
      volumes:
        - name: app
          emptyDir: {}
