env:
  open:
    DISABLE_API: false

## Ingress for load balancer
ingress:
  enabled: true

## Chartmuseum Ingress annotations
##
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"

## Chartmuseum Ingress hostnames
## Must be provided if Ingress is enabled
##
  hosts:
    - name: chartmuseum.35.238.195.135.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum-tls