bases:
  - ../../base

namespace: hipster-shop

patchesStrategicMerge:
  - increase-replicas.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: cartservice
    path: set-env.yaml