apiVersion: v1
data:
  nginx.conf: |
    worker_processes  1;
    error_log  /dev/stderr;

    events {
        worker_connections  1024;
    }

    http {
        server {
            #listen 80;
            listen 443 ssl;

            access_log /dev/stdout;

            ssl_certificate         /vault/secrets/tls.crt;
            ssl_certificate_key     /vault/secrets/tls.key;

            root /usr/share/nginx/html;
            index index.html;

            location = /basic_status {
                stub_status;
            }
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/service: "https://vault.vault:8200"
        vault.hashicorp.com/role: "otus"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-tls.crt: "pki_int/issue/example-dot-ru"
        vault.hashicorp.com/agent-inject-template-tls.crt: |
          {{- with secret "pki_int/issue/example-dot-ru" "common_name=asd.example.ru" "ttl=5m" -}}
          {{ .Data.certificate }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-tls.key: "pki_int/issue/example-dot-ru"
        vault.hashicorp.com/agent-inject-template-tls.key: |
          {{- with secret "pki_int/issue/example-dot-ru" "common_name=asd.example.ru" "ttl=5m" -}}
          {{ .Data.private_key }}
          {{- end }}
    spec:
      serviceAccountName: vault-auth
      containers:
        - name: nginx
          image: nginx:1.19.0-alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx
          ports:
            - name: https
              containerPort: 443
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        
      
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: https
      protocol: TCP
      port: 443
    # - name: http
    #   protocol: TCP
    #   port: 80