nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
              - infra-pool

tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule