prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

    tolerations:
      - key: node-role
        operator: Equal
        value: infra
        effect: NoSchedule

grafana:
  ingress:
    enabled: true
    annotations: {
      kubernetes.io/ingress.class: nginx
    }
    path: /
    hosts:
      - grafana.35.238.72.0.xip.io
  additionalDataSources:
    - name: loki
      type: loki
      access: proxy
      url: http://loki-stack.observability:3100