apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-production"
  name: shop
  labels:
    app: frontend
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: {{ .Values.service.port }}
            path: /
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: shop-tls